Note: Whenever there is an "error" in the output, it is due to the try except block and is not an actual error.
